### ISSUE TITLE
Improve method description sent to llm

### ISSUE THREAD

**Issue by ingig** [PLangHQ/plang#48]
Currently only primative variables(int, string, bool, etc.) are supported in method in Progam.cs

Need to restructure the method description send currently to llm, this happens in TypeHelper.GetMethodsAsString
I've looked an NJsonSchema, it just too verbose 

Here is suggestion with support for classes/records

Here is c# code in Program.cs
```csharp
public record OutputTarget(string[] cssSelectors, 
	[Description("appendTo|afterElement|beforeElement|prependTo|insertAfter|insertBefore")] 
	string elementPosition = "appendTo",
	[Description("innerHTML|innerText|outerHTML|outerText")]
	string contentProperty = "innerHTML", 
	bool overwriteIfExists = true);
[Description("Add, append or replace content in the output stream at a specific css selector")]
public async Task AddOrReplace(OutputTarget outputTarget)
{
.....
}
```

this would translate into something like this
```yaml
[{
    Function: "AddOrReplace(OutputTarget cssSelector, string? name)",
    Description: "Add, append or replace content in the output stream at a specific css selector",
    ReturnType: "void",
    Parameters: [
        {
            Type: "OutputTarget",
            Name: "outputTarget",
            Parameters: [
                {   
                    type: "string[]",
                    name: "cssSelectors", 
                    required: true
                }, 
                {
                  type: "string",
                  name: "elementPosition",
                  defaultValue : "appendTo",
                  description: "appendTo|afterElement|beforeElement|prependTo|insertAfter|insertBefore"                  
                },
                {
                  type: "string",
                  name: "contentProperty",
                  defaultValue: "innerHTML",
                  description: "innerHTML|innerText|outerHTML|outerText"
                },
                {
                  type: "bool",
                  name: "overwriteIfExists",
                  defaultValue: true
                } 
            ]
        },
        {
          type: "string",
          name: "name",
          optional: true
        }
    ]
}]
```

it supports, 
- description, for method and properties
- ? will determine if it´s required or not
- defaultValues can be defined

Having object as parameters into Program.cs method is better I think, it will allow for more detailed structure llm request and improved validation.

**It also allows for refactoring:**
let say the cssSelector variable in OutputTarget is changed to 'selector', this could the put into the description that this change was made. When the runtime fails on old build, it can read the description and determine what the new property is. the description can even have instruction on how to convert the property.

**It also allows for nested properties:**
if a Program.Method calls another Program.Method is can offer both properties fully to the user. 
let say you create a new module with a method WhatModulesAreAvailable this would use the FileModule to read files, it could have the method signature, WhatModulesAreAvailable(string filter, ReadFileOptions options), this would cascade the properties down to the FileModule, but allowing the developer to fully control all those settings. In this case we are assuming that ReadFile has ReadFileOptions  as parameter.
